ProyectoGym/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from django.conf import settings
from django.views.static import serve

from ProyectoGymApp import views
from ProyectoGymAppCliente import views
from ProyectoGymAppAdmin import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('ProyectoGymApp.urls')),
    path('', include('ProyectoGymAppCliente.urls')),
    path('', include('ProyectoGymAppAdmin.urls')),
]

urlpatterns += [
    re_path(r'^img/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

ProyectoGymAppCliente/urls.py
from django.urls import path

from ProyectoGymAppCliente import views
from ProyectoGymAppAdmin import views as viewsadmin
from ProyectoGymAppAdmin.models import Entrenamiento

urlpatterns = [
    path('', views.inicio, name="Inicio"),
    path('evaluacion', views.evaluacion, name="Evaluacion"),
    path('ejercicios', views.buscarejercicios, name="Ejercicios"),
    path('infosuplementacion', views.infosuplementacion, name="InfoSuplementacion"),
    path('informacion', views.informacion, name="Informacion"),
    path('artentrenamiento', views.articulos_entrenamiento,
         name="ArticulosEntrenamiento"),
    path('articulo/<int:pk>', views.articulo, name="Articulo"),
    path('planes_recomendados/<int:pk_evaluacion>',
         views.planes_recomendados, name="PlanesRecomendados"),
    path('mostrar_plan/<int:pk_plan>', views.mostrar_plan_entrenamiento,
         name="MostrarPlanEntrenamiento"),
    path('mostrar_rutina/<int:pk_plan>/<int:pk_rutina>',
         views.mostrar_rutina, name="MostrarRutina"),
    path('galeria', views.galeria, name="Galeria"),
    path('uploadgaleria', views.uploadgaleria, name="Uploadgaleria"),
    path('editgaleria/<int:pk>', views.editgaleria, name="Editgaleria"),
    path('deletegaleria/<int:pk>', views.deletegaleria, name="Deletegaleria"),
    path('mostrarrecetacliente', views.mostrarrecetas,
         name="Mostrarrecetascliente"),
    path('mostrarofertacliente', views.mostrarofertas,
         name="Mostrarofertascliente"),

    path('verificar', views.verificar, name="Verificar"),
    path('mostrar_plan_nutricional/<int:pk_plan>/<int:duracion_meses>/<str:initial_date>', views.mostrar_plan_nutricional,
         name="MostrarPlanNutricional"),
    path('mostrarplannxdia/<int:pk_plan>/<str:date>',
         views.mostrarPlannXdia, name="MostrarPlanNutricionalXdia")
]

ProyectoGymAppCliente/models.py
from io import open_code
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.enums import Choices
from django.db.models.fields import DateField
from ProyectoGymApp.models import Profile
import datetime
import os


class Ejercicio(models.Model):

    DIFFICULTY = (
        ('P', 'Principiante'),
        ('I', 'Intermedio'),
        ('A', 'Avanzado'),
    )

    CATEGORY = (
        ('E', 'Estiramientos'),
        ('PC', 'Peso corporal'),
        ('B', 'Barra'),
        ('M', 'Mancuernas'),
        ('P', 'Polea'),
        ('BE', 'Banda Elástica')
    )

    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=250)
    difficulty = models.CharField(max_length=1, choices=DIFFICULTY)
    category = models.CharField(max_length=2, choices=CATEGORY)
    video = models.URLField()
    muscles_involved = models.ManyToManyField('Muscles')

    def __str__(self):
        return self.name


def filepath(request, filename):
    old_filename = filename
    timeNow = datetime.datetime.now().strftime('%Y%m%d%H:%M:%S')
    filename = "%s%s" % (timeNow, old_filename)
    return os.path.join('uploads/', filename)


class Muscles(models.Model):

    name = models.CharField(max_length=50, unique=True)
    img = models.URLField(null=True)

    def __str__(self):
        return self.name


class Rutina(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=300, null=True, blank=True)
    ejercicios = models.ManyToManyField(Ejercicio, through='Ejercicio_Rutina')

    def __str__(self):
        return self.name


class Ejercicio_Rutina(models.Model):
    ejercicio = models.ForeignKey(Ejercicio, on_delete=models.CASCADE)
    rutina = models.ForeignKey(Rutina, on_delete=models.CASCADE)
    sets = models.IntegerField()
    sets_adicionales = models.IntegerField(
        verbose_name="Sets Adicionales", default=0)
    repeticiones = models.IntegerField(
        verbose_name="Repeticiones/Pasos", default=0)
    rep_adicionales = models.IntegerField(
        verbose_name="Repeticiones Adicionales", default=0)
    fallo = models.BooleanField(default=False)

    def __str__(self):
        return "{}. {}".format(self.rutina.name, self.ejercicio.name)


class PlanEntrenamiento(models.Model):

    LEVEL = [
        ('P', 'Principiante'),
        ('I', 'Intermedio'),
        ('A', 'Avanzado'),
    ]

    OBJECTIVE = [
        ('H', 'Hipertrofia muscular'),
        ('QyB', 'Quemar grasa y bajar de peso'),
    ]

    name = models.CharField(max_length=100, unique=True)
    img = models.URLField(null=True)
    description = models.CharField(max_length=300, null=True, blank=True)
    rutinas = models.ManyToManyField(
        Rutina, through='Rutina_PlanEntrenamiento')
    level = models.CharField(max_length=1, choices=LEVEL, default='P')
    objective = models.CharField(max_length=5, choices=OBJECTIVE, null=True)

    def __str__(self):
        return self.name


class Rutina_PlanEntrenamiento(models.Model):
    rutina = models.ForeignKey(Rutina, on_delete=CASCADE)
    plan_entrenamiento = models.ForeignKey(
        PlanEntrenamiento, on_delete=CASCADE)
    DAYS_OF_WEEK = [
        ('L', 'Lunes'),
        ('M', 'Martes'),
        ('K', 'Miercoles'),
        ('J', 'Jueves'),
        ('V', 'Viernes'),
        ('S', 'Sábado'),
        ('D', 'Domingo')
    ]
    days_of_week = models.CharField(
        max_length=1, choices=DAYS_OF_WEEK)
    week = models.IntegerField(null=True)
    month = models.IntegerField(null=True)

    def __str__(self):
        return "{} - {} {} / Semana {} / Mes {}".format(
            self.plan_entrenamiento.name, self.rutina.name, self.get_days_of_week_display(), self.week, self.month)


class Food(models.Model):
    name = models.CharField(max_length=100, unique=True)
    caloriasXgr = models.IntegerField(null=True)
    ulrPhoto = models.URLField(null=True)

    def __str__(self):
        return self.name


class PlanNutricional(models.Model):
    OBJECTIVE = [
        ('H', 'Hipertrofia muscular'),
        ('QyB', 'Quemar grasa y bajar de peso'),
    ]
    name = models.CharField(max_length=200, unique=True)
    description = models.CharField(max_length=300, null=True)
    objective = models.CharField(max_length=5, choices=OBJECTIVE, null=True)

    def __str__(self):
        return self.name


class NutritionalPlanDate(models.Model):
    planNutricional = models.ForeignKey(PlanNutricional, on_delete=CASCADE)
    month = models.IntegerField()
    day = models.IntegerField()
    date = models.DateField()


class ListaIngredientes(models.Model):
    plan_nutricional = models.ManyToManyField(
        PlanNutricional, through='Comida')
    food = models.ManyToManyField(Food, through='Opciones')
    description = models.CharField(max_length=200, unique=True, null=True)

    def __str__(self):
        return "{}".format(self.description)


class Comida(models.Model):

    COMIDA = [
        (1, 'Comida 1'),
        (2, 'Comida 2'),
        (3, 'Comida 3'),
        (4, 'Comida 4'),
        (5, 'Comida 5'),
        (6, 'Comida 6'),
        (7, 'Comida 7'),
        (8, 'Comida 8'),
    ]

    plan_nutricional = models.ForeignKey(PlanNutricional, on_delete=CASCADE)
    lista_ingredientes = models.ForeignKey(
        ListaIngredientes, on_delete=CASCADE, null=True)
    num_comida = models.IntegerField(choices=COMIDA)
    num_lista = models.IntegerField(null=True)

    def __str__(self):
        return "{} / Comida {} - {}) {}".format(self.plan_nutricional.name, self.num_comida, self.num_lista, self.lista_ingredientes)


class Opciones(models.Model):
    lista_ingredientes = models.ForeignKey(
        ListaIngredientes, on_delete=CASCADE)

    food = models.ForeignKey(Food, on_delete=CASCADE)

    def __str__(self):
        return "{} - Opciones ({})".format(self.lista_ingredientes, self.food.name)


class SeguimientoNutricional(models.Model):
    PlanNutricional = models.ForeignKey(PlanNutricional, on_delete=CASCADE)
    comida = models.ForeignKey(Comida, on_delete=CASCADE, null=True)
    date = models.DateField()
    completado = models.BooleanField(default=False)


class Evaluation(models.Model):
    EXP = (
        ('P', 'Principiante'),
        ('I', 'Intermedio'),
        ('A', 'Avanzado'),
    )

    OBJECTIVE = (
        ('H', 'Hipertrofia muscular'),
        ('QyB', 'Quemar grasa y bajar de peso'),
    )

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    height = models.DecimalField(max_digits=10, decimal_places=2)
    weight = models.DecimalField(max_digits=10, decimal_places=2)
    experience = models.CharField(max_length=1, choices=EXP)
    objective = models.CharField(max_length=5, choices=OBJECTIVE)
    training_plan = models.ForeignKey(
        PlanEntrenamiento, on_delete=CASCADE, null=True)
    nutritional_plan = models.OneToOneField(
        PlanNutricional, on_delete=CASCADE, null=True)
    date = models.DateTimeField(auto_now=True, null=True)
    duration = models.IntegerField(default=3)
    endDate = models.DateField(null=True, blank=True)


class Gallery(models.Model):

    title = models.CharField(max_length=50)
    description = models.CharField(max_length=150)
    image = models.ImageField(upload_to=filepath, null=True, blank=True)

ProyectoGymAppCliente/forms.py
from typing import ValuesView
from django import forms
from django.core.exceptions import RequestDataTooBig
from django.db.models import query
from django.db.models.base import Model
from django.forms.fields import MultipleChoiceField
from django.forms.models import ModelMultipleChoiceField
from django.forms.widgets import CheckboxInput, RadioSelect
from django.forms import ModelForm
from .models import Evaluation


class EvaluationForm(forms.Form):
    height = forms.DecimalField(
        max_value=2.0, decimal_places=2, label="Talla (metros): ")
    weight = forms.DecimalField(
        max_value=200.0, decimal_places=2, label="Peso (kg): ")

    EXP = (
        ('P', 'Principiante'),
        ('I', 'Intermedio'),
        ('A', 'Avanzado'),
    )

    OBJECTIVE = (
        ('H', 'Hipertrofia muscular'),
        ('QyB', 'Quemar grasa y bajar de peso'),
    )

    experience = forms.ChoiceField(label="Experiencia: ", choices=EXP)
    objective = forms.ChoiceField(label="Objetivo: ", choices=OBJECTIVE)
    duration = forms.IntegerField(
        label="Duración: ", max_value=12, min_value=1)


class EjercicioForm(forms.Form):

    CATEGORY = [
        ('E', 'Estiramientos'),
        ('PC', 'Peso corporal'),
        ('B', 'Barra'),
        ('M', 'Mancuernas'),
        ('P', 'Polea'),
        ('BE', 'Banda Elástica')
    ]

    MUSCLES = [
        (1, 'Triceps'),
        (2, 'Cuadriceps'),
        (3, 'Biceps'),
        (4, 'Trapecios'),
        (5, 'Deltoides'),
        (6, 'Antebrazos'),
        (7, 'Pectorales'),
        (8, 'Dorsales'),
        (9, 'Pantorrillas'),
        (10, 'Femorales'),
        (11, 'Gluteos'),
        (12, 'Abdominales'),
    ]

    category = forms.ChoiceField(
        choices=CATEGORY, widget=RadioSelect(attrs={'checked': True}), label='Categoria:')
    muscles_involved = forms.ChoiceField(
        choices=MUSCLES, label='Grupo muscular: ')

ProyectoGymAppCliente/templates/ProyectoGymAppCliente/articulo.html
{% extends "ProyectoGymAppCliente/base.html" %}

{% load static %}

{% block localStyles %}
<link href="{% static 'ProyectoGymAppCliente/css/listar_ejercicios.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="container bg-white p-5">
  <a href="{% url 'ArticulosEntrenamiento' %}">
    <- Regresar </a> <br> <br>
      <h1>{{ articulo.title }}</h1>
      <sub>{{ articulo.author }}</sub>
      <br> <br> <br>
      <p>{{ articulo.content }}</p>
      <img src="{{ articulo.image.url }}" alt="article image" class="w-75">
</div>

{% endblock %}

ProyectoGymAppCliente/templates/ProyectoGymAppCliente/base.html
<html>

<head>

  {% load static %}

  <!-- Bootstrap -->
  <link href="{% static 'ProyectoGymAppCliente/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Fonts -->

  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">


  <!-- Styles -->
  <link href="{% static 'ProyectoGymAppCliente/css/gym.css' %}" rel="stylesheet">
  {% block localStyles %} {% endblock %}
</head>

<body>

  <h1 class="site-heading text-center text-white d-none d-lg-block">

    <span class="site-heading-lower">Gym Unite </span>
  </h1>


  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'Inicio' %}">Gym</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item {% if request.path == '/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Inicio' %}">Inicio</a>
          </li>
          <li class="nav-item {% if request.path == '/ejercicios' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Ejercicios' %}">Ejercicios</a>
          </li>
          <li class="nav-item {% if request.path == '/infosuplementacion' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'InfoSuplementacion' %}">Informacion de Suplementos</a>
          </li>
          <li class="nav-item {% if request.path == '/ejercicios' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Mostrarrecetascliente' %}">Recetas</a>
          </li>
          <li class="nav-item {% if request.path == '/ejercicios' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Mostrarofertascliente' %}">Ofertas</a>
          </li>
          <li class="nav-item {% if request.path == '/ejercicios' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Galeria' %}">Galeria</a>
          </li>
          <li class="nav-item {% if request.path == '/verificar_imagen' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Verificar' %}">Nutricion</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Contenido cambiante -->
  {% block content %}



  {% endblock %}


  <!-- Footer -->
  <footer class="footer text-faded text-center py-5">
    <div class="container">
      <p class="m-0">
        <a href="#" class="link">
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
          </span>
        </a>
        <a href="#" class="link">
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
          </span>
        </a>
        <a href="#" class="link">
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
          </span>
        </a>
      </p>
      <p class="m-0 mbt">
        <a href="sample.html" class="link">Política de privacidad</a> ·
        <a href="sample.html" class="link">Aviso legal</a> ·
        <a href="sample.html" class="link">Cookies</a>
      </p>
      <p class="m-0 mbt1">&copy; Gimnasio 2020</p>
    </div>
  </footer>

  <!-- Bootstrap -->
  <script src="{%static 'ProyectoGymAppCliente/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{%static 'ProyectoGymAppCliente/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

ProyectoGymAppCliente/templates/ProyectoGymAppCliente/editgaleria.html
{% extends "ProyectoGymAppCliente/base.html" %}

{% load static %}

{% block content %}

<html lang="es">
<head>
    <meta charset="UTF-8">
    <title> Formulario de Registro</title>
    <meta name="viewport" content="width=device-width, user-scalable=no. initial-scale=1.0,
    maximum-scale=1.0, minimum-scale=1.0">
    <link href="{% static 'ProyectoGymApp/css/styles.css' %}" rel="stylesheet">

    <style>
        
        #messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}

        body, .fw-bold{
            font-family: Vegur, 'PT Sans', Verdana, sans-serif;
            font-weight: bolder;
        }

        .card{
            margin-top: 4%;
            margin-bottom: 4%;
            box-shadow: 0 0 150px -10px white;
            background-color: rgb(211, 211, 211);
        }

        .card-header{
            background-color: rgb(65, 65, 65);
            color: white;
            text-align: center;
        }

        .form-control{
            box-sizing: border-box;
            background: none;
            outline: none;
            resize: none;
            border: 0;
            transition: all .3s;
            border-bottom: 2px solid black;
        }

	</style>

</head>
<body style="margin: 0; padding: 0; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">
    <section class="section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 contenedor">
                    <div class="card">
                        <div class="card-header">
                            <h2 class="fw-bold">EDITAR FOTO</h2>
                        </div>
                        <div class="card-body">
                            <form action="" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label for="" class="form-label">TITULO</label>
                                    <input type="text" Required name="title" value="{{ egallery.title }}" class="form-control">
                                </div>
                                <div class="mb-3">
                                    <label for="" class="form-label">DESCRIPCION</label>
                                    <input type="text" name="description" value="{{ egallery.description }}" class="form-control">
                                </div>
                                <div class="mb-3">
                                    {% if egallery.image %}
                                        <img src="{{ egallery.image.url }}" alt="image here" class="card-img-top">
                                    {% endif %}                                    
                                    <label for="" class="form-label">IMAGEN ACTUAL</label>
                                    <input type="file" name="image" class="form-control">
                                </div>
                                <button type="submit" class="btn btn-warning">ACTUALIZAR</button>
                                
                                {% for message in messages %}
                                    <p id="messages"> {{message}} </p>
                                {% endfor %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</body>

</html>


{% endblock %}

ProyectoGymAppCliente/templates/ProyectoGymAppCliente/escoger_plan_entrenamiento.html
{% extends "ProyectoGymAppCliente/base.html" %}

{% load static %}

{% block localStyles %}
{% endblock %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 card">
      <div class="card-header" style="text-align: center;">
        <h2 class="fw-bold">Planes de entrenamiento recomendados</h2>
        <p>Estos los planes de entrenamiento recomendados para ti, escoge el que más te guste</p>
      </div>
      <form method="post" style="background-color: white;" class="card-body text-center">
        {% csrf_token %}

        <div class="row row-cols-1 row-cols-md-3 g-4">
          {% for plan_entrenamiento in planes_entrenamiento %}
          <div class="col">
            <div class="card mb-3" style="max-width: 540px;">
              <div class="row g-0">
                <div class="col-md-4">
                  <img src="{{ plan_entrenamiento.img }}" alt="plan picture" class="card-img-top">
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title">{{ plan_entrenamiento.name }}</h5>
                    <p class="card-text">{{ plan_entrenamiento.description }}</p>
                    <p class="card-text">Nivel: <i>{{ plan_entrenamiento.get_level_display }}</i></p>
                    <p class="card-text">Meta: <i>{{ plan_entrenamiento.get_objective_display }}</i></p>
                    <input type="radio" id="{{ plan_entrenamiento.pk }}" name="planes_de_entrenamiento"
                      value="{{ plan_entrenamiento.pk }}" {% if forloop.first %} checked {% endif %}>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <input type="submit" value="Enviar" class="btn btn-primary">
      </form>
    </div>
  </div>
</div>


{% endblock %}

ProyectoGymAppCliente/templates/ProyectoGymAppCliente/evaluacion.html
{% extends "ProyectoGymAppCliente/base.html" %}

{% load static %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 card">
      <div class="card-header" style="text-align: center;">
        <h2 class="fw-bold">Evaluación</h2>
      </div>
      <form method="post" style="background-color: white;" class="card-body text-center">
        {% csrf_token %}
        <img src="{{ user.profile.picture.url }}" alt="profile picture" class="mb-4">

        <div class="mb-3">
          <label for="name">Nombre: </label>
          <input type="text" id="name" value="{{ user.first_name.title }}" disabled>
        </div>

        <div class="mb-3">
          <label for="surname">Apellidos: </label>
          <input type="text" id="surname" value="{{ user.last_name.title }}" disabled>
        </div>

        <div class="mb-3">
          <label for="phone">Cel: </label>
          <input type="text" id="phone" value="{{ user.profile.phone_number }}" disabled>
        </div>

        <div class="mb-3">
          <label for="email">Email: </label>
          <input type="text" id="email" value="{{ user.email }}" disabled>
        </div>

        <div class="mb-3">
          {{ form.height.label }}
          {{ form.height }}
        </div>

        <div class="mb-3">
          {{ form.weight.label }}
          {{ form.weight }}
        </div>

        <div class="mb-3">
          {{ form.experience.label }}
          {{ form.experience }}
        </div>

        <div class="mb-3">
          {{ form.objective.label }}
          {{ form.objective }}
        </div>

        <div class="mb-3">
          {{ form.duration.label }}
          {{ form.duration }}
        </div>

        <input type="submit" value="Guardar" class="btn btn-primary">
      </form>
    </div>
  </div>
</div>


{% endblock %}

ProyectoGymAppCliente/templates/ProyectoGymAppCliente/inicio.html
{% extends "ProyectoGymAppCliente/base.html" %}

{% load static %}

{% block content %}



   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{%static 'ProyectoGymAppCliente/img/suplements.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Seguridad</span>
            <span class="section-heading-lower">El mejor gimnasio</span>
          </h2>
          <p class="mb-3">Breve descripcion del servicio del gym
          </p>
         
        </div>
      </div>
    </div>
  </section>


  
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Maquinas modernas</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

ProyectoGymAppCliente/templates/ProyectoGymAppCliente/listar_ejercicios.html
{% extends "ProyectoGymAppCliente/base.html" %}

{% load static %}

{% block localStyles %}
<link href="{% static 'ProyectoGymAppCliente/css/listar_ejercicios.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="ejercicios-container">
  <a href="{% url 'Ejercicios' %}">
    <- Regresar</a> <br> <br>
      {% if not ejercicios %}
      <div class="alert alert-danger" role="alert">
        <h1>Lo sentimos, no se encontraron coincidencias</h1>
      </div>
      {% endif %}

      {% for e in ejercicios %}

      <div>
        <h1>{{ e.name.title }}</h1>
        <p><strong>Difficultad: </strong>{{ e.get_difficulty_display }}</p>
        <div class="content-media">
          <video src={{ e.video }} controls loop></video>
          <div class="muscles">
            {% for m in e.muscles_involved.all %}
            <div>
              <h5>{{ m.name.title }}</h5>
              <img src="{{ m.img }}" alt="imagen {{ m.name }}">
            </div>
            {% endfor %}
          </div>
        </div>
        <h3>Descripción</h3>
        <p class=" description">{{ e.description }}</p>
        <hr>
      </div>
      {% endfor %}
</div>

{% endblock %}